const {test,afterEach}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),ts=require('typescript'),React=require('react'),{create}=require('react-test-renderer');
const {act}=React;global.IS_REACT_ACT_ENVIRONMENT=true;
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS}}).outputText,f);
const {DiscoveryMonitoring,DiscoveryHistory,change}=require('../components/DiscoveryMonitoring.tsx');
const context={id:1,name:'Auto onderhoud',parameters:{searchTerm:'auto onderhoud',countryCode:'NL',page:1,sort:'RELEVANCE'},watched:[{id:1,ean:'9781538744017'}],last_run:null};
const history={points:[{id:1,measured_at:'2026-10-01',payload:{status:'complete',list_status:'not_observed',position:null,preview:{ratings:{count:0}}}}],demand_evidence:{rating_history:'onvoldoende',market_measurements:1,rating_measurements:1,seller_trend_available:false,price_trend_available:false,comparison:{reason:'no_previous_comparable_measurement',rating_count_delta:null,offer_count_delta:0},rating_growth:null,notice:'Ratinggroei is geen verkoopvolume.'}};
const ok=b=>({ok:true,json:async()=>b});let tree;const original=global.fetch;
afterEach(()=>{if(tree)act(()=>tree.unmount());tree=undefined;global.fetch=original;});
async function mount(type=DiscoveryMonitoring,props={api:'/api',candidateId:1}){await act(async()=>tree=create(React.createElement(type,props)));}
const text=()=>JSON.stringify(tree.toJSON());
const button=label=>tree.root.findAllByType('button').find(x=>x.children.join('')===label);
async function select(){act(()=>tree.root.findByType('select').props.onChange({target:{value:'1'}}));}
test('null zero false are different',()=>{assert.equal(change(null),'Onbekend');assert.equal(change(0),'0');assert.equal(change(false),'Geen verandering');});
test('history no sales and no fake position drop',async()=>{await mount(DiscoveryHistory,{history});assert.match(text(),/Onbekend|Geen Demand Score|geen gemeten positiedaling|not_observed/);});
test('rating growth shows derived signal not sales',async()=>{await mount(DiscoveryHistory,{history:{...history,demand_evidence:{...history.demand_evidence,rating_history:'bruikbaar',rating_growth:{rating_count_delta:8,interval_days:21}}}});assert.match(text(),/derived demand signal; geen verkopen/);});
test('mount only read-only contexts',async()=>{const calls=[];global.fetch=async(url,o)=>{calls.push(o);return ok({items:[context]});};await mount();assert.equal(calls.length,1);assert.equal(calls[0].method,undefined);assert.match(text(),/Geen scheduler/);});
test('context save explicit no run or crawl',async()=>{const calls=[];global.fetch=async(url,o)=>{calls.push([url,o]);return ok(o.method?{id:1}:{items:[context]});};await mount();const inputs=tree.root.findAllByType('input');act(()=>{inputs[0].props.onChange({target:{value:'Auto onderhoud'}});inputs[1].props.onChange({target:{value:'auto onderhoud'}});});await act(async()=>button('Context bewaren').props.onClick());assert.equal(calls.filter(([,o])=>o.method==='POST').length,1);assert.ok(calls.every(([url])=>!url.endsWith('/runs')));});
test('follow candidate explicit and bounded run duplicate click',async()=>{let resolve,count=0;global.fetch=async(url,o)=>{if(url.endsWith('/runs')){count++;return new Promise(r=>resolve=r);}return ok({items:[context]});};await mount();await select();const click=button('Opnieuw meten').props.onClick;let pending;act(()=>{pending=click();click();});assert.equal(count,1);await act(async()=>{resolve(ok({status:'partial',watched_count:1}));await pending;});assert.match(text(),/Historie blijft behouden/);});
test('uncertain network retry retains UUID',async()=>{const ids=[];global.fetch=async(url,o)=>{if(url.endsWith('/runs')){ids.push(JSON.parse(o.body).request_id);throw new Error('hidden');}return ok({items:[context]});};await mount();await select();await act(async()=>button('Opnieuw meten').props.onClick());await act(async()=>button('Opnieuw meten').props.onClick());assert.equal(ids[0],ids[1]);assert.match(text(),/Verbinding onderbroken/);assert.doesNotMatch(text(),/hidden/);});
test('expired lease offers explicit new request preparation',async()=>{global.fetch=async()=>ok({items:[{...context,last_run:{status:'running',started_at:'2026-10-01',lease_expired:true}}]});await mount();await select();assert.ok(button('Nieuwe aanvraag voorbereiden'));assert.match(text(),/75 minuten/);});
test('history GET does not start a run and renders null distinct from zero',async()=>{const calls=[];global.fetch=async(url,o)=>{calls.push([url,o]);return ok(url.endsWith('/history')?history:{items:[context]});};await mount();await select();await act(async()=>button('Historie bekijken').props.onClick());assert.ok(calls.every(([,o])=>!o.method));assert.match(text(),/Ratinghistorie|Onbekend|Historische metingen/);});
test('empty watchlist disables live run',async()=>{global.fetch=async()=>ok({items:[{...context,watched:[]}]});await mount();await select();assert.equal(button('Opnieuw meten').props.disabled,true);});
test('follow and unfollow only change watchlist with explicit actions',async()=>{const calls=[];global.fetch=async(url,o)=>{calls.push([url,o]);return ok({items:[context]});};await mount();await select();await act(async()=>button('Geselecteerde kandidaat volgen').props.onClick());await act(async()=>button('Niet meer volgen').props.onClick());const posts=calls.filter(([,o])=>o.method);assert.equal(posts.length,2);assert.ok(posts.every(([url])=>url.endsWith('/watchlist')));assert.equal(JSON.parse(posts[0][1].body).followed,true);assert.equal(JSON.parse(posts[1][1].body).followed,false);});
test('malformed backend response shows safe generic error',async()=>{global.fetch=async()=>({ok:true,json:async()=>{throw new Error('secret transport details');}});await mount();assert.match(text(),/onverwacht antwoord/);assert.doesNotMatch(text(),/secret transport details/);});
