const {test,afterEach}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),ts=require('typescript'),React=require('react'),{create}=require('react-test-renderer');
const {act}=React;global.IS_REACT_ACT_ENVIRONMENT=true;
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS}}).outputText,f);
// Isolate the Sprint 5.1 unit tests from the separately tested monitoring child.
require('../components/DiscoveryMonitoring.tsx').DiscoveryMonitoring=()=>null;
const {Discovery,CandidateView,unknown}=require('../components/Discovery.tsx');
const market=require('../../backend/tests/fixtures/comparison_scenarios.json')[0].comparison.market;
const item={id:1,ean:'9781538744017',title:'Fixture',brand:null,category:null,sources:['bol_product_list'],status:'Verder onderzoeken',reasons:['Zoekzichtbaarheid'],missing:['financial_profile','sales_volume'],evidence_quality:40,quality_notice:'Bewijsdekking, geen verkoopkans',financial_notice:'Nog geen inkoopadvies — financiële gegevens ontbreken',last_measured_at:'2026-10-07',signals:{rating_average:{value:null,provenance:null},rating_count:{value:0,provenance:{kind:'derived',source:'bol',recorded_at:'2026-10-07'}},visibility:{value:{list_position:1},provenance:{kind:'derived',source:'bol_product_list',recorded_at:'2026-10-07'}},sales_volume:{value:null,provenance:null}},market:{...market,freshness:'missing',usable_for_current_analysis:false},market_history:[]};
let tree;const originalFetch=global.fetch;
afterEach(()=>{if(tree)act(()=>tree.unmount());tree=undefined;global.fetch=originalFetch;});
const ok=b=>({ok:true,json:async()=>b});
async function mount(type=Discovery,props={api:'/api'}){await act(async()=>{tree=create(React.createElement(type,props));});}
const text=()=>JSON.stringify(tree.toJSON());
function button(label){return tree.root.findAllByType('button').find(x=>x.children.join('')===label);}
test('unknown remains distinct from zero',()=>{assert.equal(unknown(null),'Onbekend');assert.equal(unknown(0),'0');});
test('candidate explains provenance and absent sales/financial advice',async()=>{await mount(CandidateView,{item});assert.match(text(),/Nog geen inkoopadvies|financial_profile|Onbekend|derived|geen verkoopvolume|official_measured/);assert.doesNotMatch(text(),/Bol verkoopt/);});
test('loads stored candidates only on mount; no automatic live crawl',async()=>{const calls=[];global.fetch=async(url,opt)=>{calls.push([url,opt]);return ok(url.includes('capabilities')?{white_spots:{status:'unverified',reason:'Geen toegang aangetoond'}}:{items:[item],total:1});};await mount();assert.equal(calls.length,2);assert.ok(calls.every(([,o])=>!o.method));assert.match(text(),/geen actuele prijs|Onbekend|unverified/);});
test('explicit bounded collection and duplicate click blocked',async()=>{let resolve,count=0;global.fetch=async(url,o)=>{if(o.method==='POST'){count++;return new Promise(r=>resolve=r);}return ok(url.includes('capabilities')?{white_spots:{status:'unverified',reason:'Onbekend'}}:{items:[],total:0});};await mount();act(()=>tree.root.findAllByType('input')[0].props.onChange({target:{value:'fixture'}}));const click=button('Kandidaten ophalen en opslaan').props.onClick;let pending;act(()=>{pending=click();click();});assert.equal(count,1);await act(async()=>{resolve(ok({saved_candidates:1,status:'complete',notice:'Eén pagina'}));await pending;});assert.match(text(),/1 kandidaten opgeslagen/);});
test('filters passed to backend, no client guessing',async()=>{const urls=[];global.fetch=async(url)=>{urls.push(url);return ok(url.includes('capabilities')?{white_spots:{status:'unverified',reason:'Onbekend'}}:{items:[],total:0});};await mount();act(()=>tree.root.findAllByType('input')[3].props.onChange({target:{value:'0'}}));await act(async()=>button('Filters toepassen').props.onClick());assert.match(urls.at(-1),/max_sellers=0/);});
test('failed collection surfaces safe message',async()=>{global.fetch=async(url,o)=>o.method?{ok:false,json:async()=>({detail:'Bol vraagt om even te wachten.'})}:ok(url.includes('capabilities')?{white_spots:{status:'unverified',reason:'Onbekend'}}:{items:[],total:0});await mount();act(()=>tree.root.findAllByType('input')[0].props.onChange({target:{value:'fixture'}}));await act(async()=>button('Kandidaten ophalen en opslaan').props.onClick());assert.match(text(),/Bol vraagt om even te wachten/);});
