"""Immutable-in-output scoring policy; changing this requires a new version."""
POLICY = {
    "version": "scoring-nl-new-1",
    "weights": {"demand": .25, "competition": .20, "profitability": .40, "risk": .15},
    "freshness_days": {"market": [1, 3, 14], "ratings": [7, 30, 90],
                       "cost": [7, 30, 90], "operational": [30, 90, 365]},
    "demand": {"rating_anchor": 30, "estimate_anchor": 500, "rating_quality_cap": .60,
               "estimate_quality_cap": .25, "min_interval_days": 14, "max_interval_days": 60},
    "competition": {"seller_log_base": 5, "pressure_cap": 80, "pressure_weight": .8,
                    "delivery_weight": .2, "unknown_delivery_prior": 50},
    "profitability": {"margin_anchor_percent": 25, "contribution_anchor": 8, "roi_anchor_percent": 75,
                      "margin_weight": .5, "contribution_weight": .3, "roi_weight": .2},
    "risk": {"operational_weight": .5, "quality_weight": .3, "price_weight": .2,
             "bad_rating_prior": 2, "rating_prior_total": 10, "negative_share_anchor": .2,
             "price_spread_anchor": .2, "min_days": 3, "min_span": 7,
             "full_days": 7, "full_span": 30, "limited_quality": .5, "unknown_prior": 50},
    "confidence_penalty": .2,
    "caps": {"block": 0, "loss": 24, "stress_loss": 49, "weak_demand": 49,
             "high_risk": 49, "unproven_demand": 64, "confidence_below_75": 64,
             "confidence_below_50": 49, "not_ready": 74},
    "thresholds": {"weak_demand": 35, "demand_quality": .5, "high_risk": 75,
                   "risk_quality": .6, "confidence_ready": 75, "confidence_low": 50,
                   "promising": 75, "investigate": 60, "doubt": 40,
                   "profit_quality": .8, "competition_quality": .8, "profitability": 60,
                   "margin_percent": 10, "max_promising_risk": 50},
    "source_quality": {"official_measured": 1, "manual_or_imported": .9,
                       "derived": .2, "estimated": .25},
    "operational_fields": ["fragility", "handling", "obsolescence", "supplier", "inventory_exposure"],
    "history_window_days": 90,
    "financial_policy": "conservative; unchanged financial v2; current market <=24h",
}
